id: custom-task
name: Custom task
competition_type: simple
awards_medals: false
prizes: null
description: /home/harry/co-datascientist-engine/mle-bench-agent/custom-task/description.md

dataset:
  answers: custom-task/prepared/private/answers.csv
  sample_submission: custom-task/prepared/public/sample.csv

grader:
  name: accuracy
  grade_fn: mlebench.competitions.custom-task.grade:grade

preparer: mlebench.competitions.custom-task.prepare:prepare